# Generated by Django 5.2.5 on 2026-01-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_balance_sheet', 'Can view balance sheet'), ('view_reports', 'Can view reports'), ('view_project_balance', 'Can view blance'), ('view_project_investment', 'Can view investment')]},
        ),
    ]
