# Generated by Django 5.2.9 on 2026-01-05 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermissions',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_balance_sheet', 'Can view balance sheet'), ('view_reports', 'Can view reports')]},
        ),
        migrations.AddField(
            model_name='transaction',
            name='general',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finance.project'),
        ),
    ]
