# Generated by Django 5.2.5 on 2026-01-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='general',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finance.project'),
        ),
    ]
